title: Skinny Bones
description: Elevator Pitch For your website. This is displayed in search results. Connect with your audience right from the start of the journey.
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: //dindi-jekyll.github.io/skinny-bones-jekyll
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap
owner:
  name: Dind
  web: "http://www.dindi.net"
  email: "dkl@dindi.net"
  twitter: ""
  bio: ""
  avatar: ""
  google:
    plus: ""
    ad-client: ""
    ad-slot: .nan
  disqus-shortname: ""
exclude:
  - lib
  - config.rb
  - .sass-cache
  - Capfile
  - config
  - log
  - Rakefile
  - Rakefile.rb
  - tmp
  - "*.sublime-project"
  - "*.sublime-workspace"
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - node_modules
  - Gruntfile.js
  - package.json